name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install LLVM
      run: |
        sudo apt install wget -y
        wget https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo apt-key add llvm-snapshot.gpg.key
        echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-19 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-$(lsb_release -cs)-19.list
        sudo apt update -y
        sudo apt install llvm-19 clang-19 lldb-19 lld-19 g++-arm-linux-gnueabi clang-19-arm-linux-gnueabi -y
    - name: Build x86_64
      run: |
        mkdir build
        cd build
        export CC=clang
        export CXX=clang++
        cmake .. -DLLVM_INCLUDE_DIRS=/usr/include/llvm-19 -DLLVMC_INCLUDE_DIRS=/usr/include/llvm-c-19
        make -j4
        mv dcc dcc-x86_64
    - name: Build armv7
      run: |
        rm -rf build && mkdir build
        cd build
        #export CC=/usr/bin/arm-linux-gnu-gcc
        #export CXX=/usr/bin/arm-linux-gnu-g++
        cmake .. -DLLVM_INCLUDE_DIRS=/usr/include/llvm-19 -DLLVMC_INCLUDE_DIRS=/usr/include/llvm-c-19 -DCMAKE_TOOLCHAIN_FILE=../toolchain-arm.cmake
        make -j4
        mv dcc dcc-arm
    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}"|gh auth login --with-token

    - name: Update Nightly Release
      run: |
          # Check if the nightly release already exists
          if gh release view nightly-release; then
            # Update the existing release notes
            gh release edit nightly-release \
              --notes "Automated nightly release for commit ${{ github.sha }}. Not intended for use unless you're a developer" \
              --title "Nightly Release" \
              --prerelease
            
            # Upload the new artifact to the existing release
            gh release upload nightly-release ./build/dcc-x86_64 ./build/dcc-arm --clobber
          else
            # Create a new release if it doesn't exist
            gh release create nightly-release ./build/dcc-x86_64 ./build/dcc-arm \
              --notes "Automated nightly release for commit ${{ github.sha }}. Not intended for use unless you're a developer" \
              --title "Nightly Release" \
              --prerelease
          fi
