name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install LLVM 19
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://apt.llvm.org/llvm-snapshot.gpg.key -O - | sudo apt-key add -
        echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-19 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-focal-19.list
        sudo apt-get update
        sudo apt-get install -y llvm-19 clang-19 llvm-19-arm
    
    - name: Install build dependencies
      run: |
        sudo apt-get install -y build-essential cmake
    
    - name: Build for x86_64
      run: |
        mkdir build && cd build
        #if [ "${{ matrix.architecture }}" == "arm32" ]; then
          #sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
          #CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ cmake -B build -S .
        #else
          cmake .. -DLLVM_INCLUDE_DIRS=/usr/include/llvm-19 -DLLVMC_INCLUDE_DIRS=/usr/include/llvm-c-19 
        #fi
          #cmake . -DLLVM_INCLUDE_DIRS=/usr/include/llvm-19 -DLLVMC_INCLUDE_DIRS=/usr/include/llvm-c-19
        make -j4
        mv dcc ../dcc-x86_64

    - name: Build for ARM
      run: |
        rm build -rf && mkdir build && cd build
        sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
        CC=arm-linux-gnueabi-gcc CXX=arm-linux-gnueabi-g++ cmake .. -DLLVM_INCLUDE_DIRS=/usr/include/llvm-19 -DLLVMC_INCLUDE_DIRS=/usr/include/llvm-c-19
        make -j4
        mv dcc ../dcc-arm
        cd ..
        rm build -rf

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}"|gh auth login --with-token

    - name: Update Nightly Release
      run: |
          # Check if the nightly release already exists
          if gh release view nightly-release; then
            # Update the existing release notes
            gh release edit nightly-release \
              --notes "Automated nightly release for commit ${{ github.sha }}. Not intended for use unless you're a developer" \
              --title "Nightly Release" \
              --prerelease
            
            # Upload the new artifact to the existing release
            gh release upload nightly-release ./dcc-x86_64 ./dcc-arm --clobber
          else
            # Create a new release if it doesn't exist
            gh release create nightly-release ./dcc-x86_64 ./dcc-arm \
              --notes "Automated nightly release for commit ${{ github.sha }}. Not intended for use unless you're a developer" \
              --title "Nightly Release" \
              --prerelease
          fi
