name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://apt.llvm.org/llvm-snapshot.gpg.key -O - | sudo apt-key add -
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-focal-18.list
          sudo apt-get update
          sudo apt-get install -y llvm-18 clang-18 build-essential cmake

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DLLVM_INCLUDE_DIRS=/usr/include/llvm-18 -DLLVMC_INCLUDE_DIRS=/usr/include/llvm-c-18
          make -j4
          mv dcc ../dcc-x86_64

  publish:
    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Update Nightly Release
      run: |
        export NOTE="Automated nightly release for commit ${{ github.sha }}. This release contains all of the newest features. Not intended for use unless you're a developer"
        if gh release view nightly-release; then
          gh release edit nightly-release \
            --notes "$NOTE" \
            --title "Nightly Release" \
            --prerelease
          gh release upload nightly-release ./dcc-x86_64 --clobber
        else
          gh release create nightly-release ./dcc-x86_64 \
            --notes "$NOTE" \
            --title "Nightly Release" \
            --prerelease
        fi
