name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install LLVM
      run: |
        sudo apt install wget -y
        wget https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo apt-key add llvm-snapshot.gpg.key
        echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain-$(lsb_release -cs)-18.list
        sudo apt update -y
        sudo apt install llvm-18 clang-18 lldb-18 lld-18 -y
        sudo apt install libllvm18-dev -y
    - name: cmake
      run: |
        mkdir build
        cd build
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake .. -DLLVM_DIR=/usr/lib/llvm-14/lib/cmake/llvm -DLLVM_INCLUDE_DIRS=/usr/include/llvm-14
        make -j4
